#!/usr/bin/env python
"""Generate the C++ symbol header from symbols.toml.

    python tools/gen_symbols.py --toml symbols.toml --out build/gen/bof3/symbols.gen.h

symbols.toml is the only place an address is typed (docs/SCAFFOLDING.md). This
emits, for every named function and data item:

  * an address constant, `bof3::addr::Name`;
  * for a function with a signature (`ret`/`params`), exactly ONE binding of
    the bare name:
      - no `impl`  -> a macro casting the literal address to a typed function
                      pointer, so our code calls Capcom's code;
      - `impl`     -> an ordinary prototype for OUR function, plus an
                      `orig::Name` pointer to the address it displaced.
    Call sites are the same in both cases, so taking over a function is: write
    it, add `impl` to its symbols.toml entry, add one BOF3_INJECT line.
  * for data with a `ctype`: a macro giving a typed lvalue (scalar) or a typed
    pointer to element 0 (`count` present).

The output contains addresses and names only — our work product, not game data.
It is still generated into the build tree rather than committed, so it cannot
drift from symbols.toml.
"""
import argparse, os, re, sys, tomllib

IDENT = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
CCS = {'__cdecl', '__stdcall', '__fastcall', '__thiscall'}


def fail(msg):
    sys.exit(f'gen_symbols: {msg}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--toml', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    with open(a.toml, 'rb') as f:
        t = tomllib.load(f)
    meta = t['meta']
    lo, hi = meta['image_base'], meta['image_base'] + meta['size_of_image']

    seen_name, seen_addr = {}, {}
    def check(kind, e):
        name, pc = e.get('name'), e.get('pc')
        if not name or not IDENT.match(name):
            fail(f'{kind} at {pc!r}: bad or missing name {name!r}')
        if not isinstance(pc, int) or not lo <= pc < hi:
            fail(f'{name}: pc {pc!r} is outside the image {lo:#x}..{hi:#x}')
        if name in seen_name:
            fail(f'{name}: name bound twice ({seen_name[name]:#x} and {pc:#x})')
        if pc in seen_addr:
            fail(f'{pc:#x}: address bound twice ({seen_addr[pc]} and {name})')
        seen_name[name], seen_addr[pc] = pc, name

    out = []
    w = out.append
    w('// GENERATED by tools/gen_symbols.py from symbols.toml. Do not edit.')
    w('// Every number in this file is an address inside BOF3.exe (CLAUDE.md rule 3).')
    w('#pragma once')
    w('#include <cstdint>')
    w('')
    w('namespace bof3::image {')
    w(f'inline constexpr std::uint32_t kBase = {meta["image_base"]:#x};')
    w(f'inline constexpr std::uint32_t kTimestamp = {meta["pe_timestamp"]:#x};')
    w(f'inline constexpr std::uint32_t kSizeOfImage = {meta["size_of_image"]:#x};')
    w('}  // namespace bof3::image')
    w('')

    funcs = sorted(t.get('func', []), key=lambda e: e.get('pc', 0))
    datas = sorted(t.get('data', []), key=lambda e: e.get('pc', 0))
    blocks = sorted(t.get('block', []), key=lambda e: e.get('pc', 0))
    for e in funcs: check('func', e)
    for e in datas: check('data', e)
    for e in blocks: check('block', e)

    w('namespace bof3::addr {')
    for e in blocks + datas + funcs:
        w(f'inline constexpr std::uint32_t {e["name"]} = {e["pc"]:#x};')
    w('}  // namespace bof3::addr')
    w('')

    ours, theirs = [], []
    for e in funcs:
        if 'impl' in e and 'ret' not in e:
            fail(f'{e["name"]}: has impl but no signature')
        if 'ret' not in e:
            continue
        if 'params' not in e:
            fail(f'{e["name"]}: ret without params (write "void" for none)')
        cc = e.get('cc', '__cdecl')
        if cc not in CCS:
            fail(f'{e["name"]}: unknown calling convention {cc!r}')
        if 'impl' in e:
            if not os.path.isfile(os.path.join(os.path.dirname(os.path.abspath(a.toml)), e['impl'])):
                fail(f'{e["name"]}: impl file {e["impl"]} does not exist')
            ours.append((e, cc))
        else:
            theirs.append((e, cc))

    w('// --- Functions still Capcom\'s: the name is the original address. ---')
    for e, cc in theirs:
        w(f'#define {e["name"]} (reinterpret_cast<{e["ret"]} ({cc} *)({e["params"]})>({e["pc"]:#x}))')
    w('')
    w('// --- Functions that are ours: the name is our implementation. ---')
    for e, cc in ours:
        w(f'// {e["impl"]}')
        w(f'extern "C" {e["ret"]} {cc} {e["name"]}({e["params"]});')
    w('')
    w('// The address each of ours displaced. After BOF3_INJECT its first five')
    w('// bytes are a jmp to ours, so this is for the detour layer, not for calling.')
    w('namespace bof3::orig {')
    for e, cc in ours:
        w(f'inline const auto {e["name"]} = reinterpret_cast<{e["ret"]} ({cc} *)({e["params"]})>({e["pc"]:#x});')
    w('}  // namespace bof3::orig')
    w('')

    w('// --- Data. Scalars are lvalues; arrays are pointers to element 0. ---')
    for e in datas:
        if 'ctype' not in e:
            continue
        ty = e['ctype']
        if 'count' in e:
            w(f'#define {e["name"]} (reinterpret_cast<{ty} *>({e["pc"]:#x}))')
            w(f'inline constexpr unsigned {e["name"]}_count = {e["count"]};')
        else:
            w(f'#define {e["name"]} (*reinterpret_cast<{ty} *>({e["pc"]:#x}))')
    w('')

    text = '\n'.join(out)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    # Leave the file alone when nothing changed so the build does not re-run.
    try:
        with open(a.out, encoding='utf-8') as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(a.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'gen_symbols: {len(ours)} ours, {len(theirs)} callable originals, '
          f'{len(funcs)} functions named -> {a.out}')


if __name__ == '__main__':
    main()
